export const PHOTO_ALBUMS = [
  {
    name: 'Jakarta - Car Free Day',
    slug: '2023-jakarta-car-free-day',
    date: '2023-06-11 00:00',
    photos: [
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0613_NyVo9Id9st.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0617_Gqga2aJnZ.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0618_nKWv4xEFY.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0620_c_JJ6UbAu.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0622_sK4enjpc0.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0627_biYQ4lW_n.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0634_VtQvAespo.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0640_2kvVQFqZ15.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0650_wiChsH4xk.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0653_TAOd1FyRi.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0654_ul_s0DggE.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0655_1u3e55j6W.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0657_8p5-10Rahp.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0662_pNQ7NxsrT.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0663_GgQ5j0dgS.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0666_4a8GN9brl.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0667_--G5g_t7E.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0670_loQk9sJxa.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0672_IRQ-D_TIvF.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0675_O8BuOJ2oc.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0677__V0ci07VO.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0680_A-NPFxE_Z.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0683_cJSVqn2ob.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0684_PZbfrQQXl.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0686_3Z-R_s-St.JPG',
      'https://ik.imagekit.io/kvn/Car_Free_Day/DSCF0691_gLhTEsJXF.JPG',
    ],
  },
  {
    name: 'Jakarta - PIK',
    slug: '2023-jakarta-pik',
    date: '2023-01-23 00:00',
    photos: [
      'https://ik.imagekit.io/kvn/PIK/DSCF0461_ebkcmXZMf.JPG',
      'https://ik.imagekit.io/kvn/PIK/DSCF0464_QXdi1qiff.JPG',
      'https://ik.imagekit.io/kvn/PIK/DSCF0467_AY4pEAc7F.JPG',
      'https://ik.imagekit.io/kvn/PIK/DSCF0470_W_tt6QWiQ.JPG',
      'https://ik.imagekit.io/kvn/PIK/DSCF0474_MYue8287B0.JPG',
      'https://ik.imagekit.io/kvn/PIK/DSCF0477_cS1YcsicL.JPG',
      'https://ik.imagekit.io/kvn/PIK/DSCF0482_Slmq-VKXe.JPG',
      'https://ik.imagekit.io/kvn/PIK/DSCF0483_zyeKFqs9j.JPG',
      'https://ik.imagekit.io/kvn/PIK/DSCF0484_GEhCIQAeFP.JPG',
      'https://ik.imagekit.io/kvn/PIK/DSCF0497_dsslEHxxSQ.JPG',
      'https://ik.imagekit.io/kvn/PIK/DSCF0504_xfVmhfzqe.JPG',
      'https://ik.imagekit.io/kvn/PIK/DSCF0507_ALZceBnUg.JPG',
      'https://ik.imagekit.io/kvn/PIK/DSCF0509_K2HvLGbFV0.JPG',
      'https://ik.imagekit.io/kvn/PIK/DSCF0513_VsEXmwhE0.JPG',
      'https://ik.imagekit.io/kvn/PIK/DSCF0515_vuYtjYEtg.JPG',
    ],
  },
  {
    name: 'Yogyakarta',
    slug: '2022-yogyakarta',
    date: '2022-12-17 00:00',
    photos: [
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0274_VfU8k2f_j.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0277_RNDqAKlWy.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0287_hOq3dNVa0.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0297_7cwWX7ata.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0298_meFXMC_OlB.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0300_sJNokXY-c.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0301_382kMxyQJ.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0308_uXOuR6L8W.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0318_-p_wpqUgI6.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0320_Y1QyAlgdg.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0321_aw77BNLvB1.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0329_3gji3AMvI.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0334_-ZN5WhhYP.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0337_L6fl5svFa.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0343_813P4fNe6Q.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0344_oiAEcHila.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0347_PnY1uND9w.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0348_w4ektHFf7.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0358_QQok5-7Yd.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0363_tkS7m94FL.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0368_yjhj8Pb_p.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0378_VexVatBsn.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0379_pAp_u6Dg6.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0383_-hLpqRr1Y.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0399_sIPmKxshR.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0412_GQI5h1yHM.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0418_086MJuIbz.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0426_8L2gBaOSXW.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0427__dHnTxpzZ.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0435_AM1TjoVOP.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0441_Hk77_8ApO.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0451_0mO5uGf8y.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0452_0mepmo1ra.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta_2/DSCF0458_Gc_PQ2Rnl.JPG',
    ],
  },
  {
    name: 'Bogor',
    slug: '2022-bogor',
    date: '2022-02-02 00:00',
    photos: [
      'https://ik.imagekit.io/kvn/Bogor/DSCF0158_xkOT3UMDe.JPG',
      'https://ik.imagekit.io/kvn/Bogor/DSCF0161_uQ_Hp_egmSy.JPG',
      'https://ik.imagekit.io/kvn/Bogor/DSCF0163_PXp-RiKdE.JPG',
      'https://ik.imagekit.io/kvn/Bogor/DSCF0164_4_k6eat7fep3.JPG',
      'https://ik.imagekit.io/kvn/Bogor/DSCF0167_JLcrRNw18.JPG',
      'https://ik.imagekit.io/kvn/Bogor/DSCF0171_zgsIAgiU9.JPG',
      'https://ik.imagekit.io/kvn/Bogor/DSCF0172_V5ucDspg7.JPG',
      'https://ik.imagekit.io/kvn/Bogor/DSCF0174_QYUCyGSrp.JPG',
      'https://ik.imagekit.io/kvn/Bogor/DSCF0180_r_vzd9LZd.JPG',
      'https://ik.imagekit.io/kvn/Bogor/DSCF0182_J3Yalay95.JPG',
      'https://ik.imagekit.io/kvn/Bogor/DSCF0185_vnpf4nCG40.JPG',
      'https://ik.imagekit.io/kvn/Bogor/DSCF0186_E1HW-gqGCg.JPG',
      'https://ik.imagekit.io/kvn/Bogor/DSCF0190_BPSZiQ2YZrd.JPG',
      'https://ik.imagekit.io/kvn/Bogor/DSCF0195_gurMEnluM.JPG',
      'https://ik.imagekit.io/kvn/Bogor/DSCF0198_GcRiR7sjz.JPG',
      'https://ik.imagekit.io/kvn/Bogor/DSCF0200_FETLaupSZ.JPG',
      'https://ik.imagekit.io/kvn/Bogor/DSCF0204_1xmuTcPNBLR7.JPG',
    ],
  },
  {
    name: 'Yogyakarta',
    slug: '2021-yogyakarta',
    date: '2021-09-28 00:00',
    photos: [
      'https://ik.imagekit.io/kvn/Yogyakarta/DSCF9185_N_BP4TMlme.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta/DSCF9207_46-WccHyf.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta/DSCF9209_SvXLW6Hnx.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta/DSCF9210_hvpQo_XlA207.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta/DSCF9217_xaR8lxIBA.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta/DSCF9235_FGi5fIAvz.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta/DSCF9246_M539MbHww.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta/DSCF9257_CtNt0O6lfrn.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta/DSCF10080_OZGsUKYUjv.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta/DSCF10088_ZkSE0GU-a.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta/DSCF10097_NMvKmuF_c.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta/DSCF10101_MXtk4pY0q.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta/DSCF10104_dToAT7zvt.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta/DSCF10105_IhVR553av.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta/DSCF10108_j_f0_C02p.JPG',
      'https://ik.imagekit.io/kvn/Yogyakarta/DSCF10120_xMnJIXOPJ.JPG',
    ],
  },
  {
    name: 'Tangerang - The Breeze',
    slug: '2020-tangerang-the-breeze',
    date: '2020-10-17 00:00',
    photos: [
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9045_fK64n7eD7ai.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9048_mE-5p3dAc9Q.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9053_txtJdKZz-kJ.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9056_ZdrTLyMNDFC.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9065__Zozs6jpRKdN.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9070_hnouQ1acnlW.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9074_FPbDfV8sy1G.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9078_UkleL3TMKb8.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9079_S4LkJbnd7dmL.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9085_EkTHW0tFJNiw.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9087__XGlexzPkyS.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9090_DtT1h4-2VFZm.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9096_1odVamTrgpB.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9104_SmaTfzWifkI.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9109_ojGERNorVWB.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9112_rnnunGuaNSS.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9114_bucRy-B2hnm.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9120_5Fub9bTRx7wv.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9125_Tcbhnjw70E6.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9126_8B5ra4TTrcV.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9132_YFnUW5XkNqOO.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9135_ek2UgsY1A82.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9138_0ai1pb2ADAQO.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9148_EksBdzZffi1.JPG',
      'https://ik.imagekit.io/kvn/The_Breeze/DSCF9154_u9GbEvMQb0XI.JPG',
    ],
  },
  {
    name: 'Tangerang - Intermoda',
    slug: '2020-tangerang-intermoda',
    date: '2020-10-04 00:00',
    photos: [
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9729_N5V7PsTBQNPY.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9730_SOP-3aDzmbi.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9731_3g88GYjTtChO.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9732_PDQl9kstp28.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9739_gZ0WS6HEZhuA.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9740_hkAlmK4wYRy.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9743_At2xwgLptwG.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9749_gEGWWJ4E2Bt.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9754_mAs4ietQeC4.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9760_V79BfJ0DeO2j.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9763_f1fKQoxe8hy.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9766_MxGy21C7EbM.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9767_0_sLF8yzon-.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9768_jAdoDfQXlJSu.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9770_EUTsGOgNQYW.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9775_BiNgEhQxhDV.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9779_SQbzyZQ3PaA.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9782_DKhz8B6YQ5c4.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9783_T-YQhRthq_NP.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9787_zoxG7QT70z3Y.JPG',
      'https://ik.imagekit.io/kvn/Intermoda/DSCF9788_vg_N6HrUlIbl.JPG',
    ],
  },
  {
    name: 'Singapore',
    slug: '2019-singapore',
    date: '2019-11-01 00:00',
    photos: [
      'https://ik.imagekit.io/kvn/Singapore/DSCF1584_BYiqGNImAtXI.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1604_rQY8MlKCj1.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1618_r3mQ9IzhLI.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1621_ACCfNPC1yq.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1643_5_ADHxjvEMR.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1652_nwBcmNrmzBU.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1675_yzz4ToRlTVyp.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1691_irsYeNRAmMs.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1696_I5funrUYBM.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1700_XDDeYlQQ5ZS.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1716_HLHOHou1vC.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1720_XVdiJoGccS.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1730_MYLFqTFJt3ea.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1736_VGKL3tMENyN.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1747_86-R4NLxJXM.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1756_ZPfJBh0NUx.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1768_US5WOVhZTNa.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1777_VBmffMKgyyX.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1781_olFqIdkUyd.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1785_SHBBkPys5M.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1788_k2L-GDdWyo-.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1791_iy0OdPEvua.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1929_dEUPTR8ZOd.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1937_AUMtS8jfpN.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1943_TzfIeXshdP.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1946_m7jnc3BhC1h.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1961_Bi2CA6dljV2.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1965_7bkw_0HjA9u.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1978_Pt_S3IQfHTe.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1980_Owtjc_lbMZI.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF1987_JJf9gQ5pYJX.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF2049_LgHy98FTht.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF2053_m50E5JHNhAP.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF2072_jeq8b7_Cwi.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF2082_ICNQ6gUbpa.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF2093_2Zk1qYNgBrc.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF2094_lerfq-qO05.JPG',
      'https://ik.imagekit.io/kvn/Singapore/DSCF2099_W2lBBSGahx.JPG',
    ],
  },
];
